(()=>{const $=id=>document.getElementById(id);let inv=JSON.parse(localStorage.getItem('viking-rpg-v18')||'{"chests":0,"arrows":{"gelo":1,"fogo":1},"runes":[],"gear":[]}');let activePower=null,powerUntil=0,baseTargetScale=1;
function saveR(){localStorage.setItem('viking-rpg-v18',JSON.stringify(inv));updateDock()}function updateDock(){let d=$('powerDock');if(!d)return;d.style.display=running?'flex':'none';let i=$('liveIce'),f=$('liveFire');if(i)i.textContent='❄️ '+(inv.arrows.gelo||0);if(f)f.textContent='🔥 '+(inv.arrows.fogo||0)}
function ensureUI(){let home=$('home');if(!home||$('openRewards'))return;let b=document.createElement('button');b.className='btn sub';b.id='openRewards';b.textContent='🎁 TESOUROS • RUNAS • PODERES';let shopBtn=$('openShop');shopBtn.parentNode.insertBefore(b,shopBtn.nextSibling);let card=home.parentNode,p=document.createElement('div');p.className='panel';p.id='rewards';p.innerHTML='<h3>🎁 SALÃO DE TESOUROS</h3><div id="rewardHub"></div><button class="btn" data-reward-back>VOLTAR</button>';card.appendChild(p);b.onclick=()=>{document.querySelectorAll('.panel').forEach(x=>x.classList.remove('open'));home.style.display='none';p.classList.add('open');render()};p.querySelector('[data-reward-back]').onclick=()=>{p.classList.remove('open');home.style.display='block'};render()}
function rarity(){let r=Math.random();return r<.08?'lendario':r<.28?'epico':r<.62?'raro':'comum'}
function openChest(){if(inv.chests<1)return popup('🎁 Nenhum baú disponível');inv.chests--;let r=rarity(),roll=Math.random(),msg='';if(roll<.34){let n=r==='lendario'?80:r==='epico'?45:r==='raro'?25:12;coins+=n;msg='🪙 +'+n+' moedas'}else if(roll<.68){let k=Math.random()<.5?'gelo':'fogo',n=r==='lendario'?5:r==='epico'?3:2;inv.arrows[k]=(inv.arrows[k]||0)+n;msg=(k==='gelo'?'❄️':'🔥')+' +'+n+' flechas '+k}else{let pool=[['precisao','🎯 Runa da Precisão'],['loki','🃏 Runa de Loki'],['thor','⚡ Runa de Thor'],['heimdall','👁️ Runa de Heimdall']],it=pool[Math.floor(Math.random()*pool.length)];if(!inv.runes.includes(it[0])){inv.runes.push(it[0]);msg=it[1]+' conquistada'}else{coins+=20;msg=it[1]+' repetida • 🪙 +20'}};saveR();save();hud();popup('🎁 BAÚ '+r.toUpperCase()+'<br>'+msg);render()}
function usePower(k){if(!running)return popup('⚡ Use os poderes durante uma partida');if(k==='gelo'&&(inv.arrows.gelo||0)>0){inv.arrows.gelo--;activePower='gelo';powerUntil=Date.now()+8000;cancelAnimationFrame(motion);popup('❄️ ALVO CONGELADO • 8s');setTimeout(()=>{if(running&&activePower==='gelo'&&Date.now()>=powerUntil){activePower=null;moveTarget()}},8050)}else if(k==='fogo'&&(inv.arrows.fogo||0)>0){inv.arrows.fogo--;activePower='fogo';powerUntil=Date.now()+10000;popup('🔥 PONTOS EM DOBRO • 10s')}else return popup('Sem flechas desse tipo');saveR();render()}
function render(){let e=$('rewardHub');if(!e)return;let pl=playerLevel(),region=pl>=10?'⚡ ASGARD':pl>=7?'🏰 FORTALEZA':pl>=4?'🌲 FLORESTA':'🏔️ FIORDE';e.innerHTML='<div class="rewardSummary"><div class="rewardTitle">🗺️ PROGRESSÃO VIKING</div><div class="rewardExplain">Região atual: <b>'+region+'</b><br>Suba o nível geral para alcançar novas regiões e tesouros.</div></div><div class="rewardSummary"><div class="rewardTitle">🎁 BAÚS</div><div class="rewardGrid"><div class="rewardBox"><b>'+inv.chests+'</b>Disponíveis</div><div class="rewardBox"><b>'+inv.runes.length+'/4</b>Runas</div></div><button class="btn" id="openChest">ABRIR BAÚ</button></div><div class="rewardSummary"><div class="rewardTitle">🏹 FLECHAS ESPECIAIS</div><button class="btn train" id="icePower">❄️ GELO ×'+(inv.arrows.gelo||0)+' • congela 8s</button><button class="btn daily" id="firePower">🔥 FOGO ×'+(inv.arrows.fogo||0)+' • pontos ×2 por 10s</button></div><div class="rewardSummary"><div class="rewardTitle">🧿 RUNAS CONQUISTADAS</div><div class="rewardExplain">'+(inv.runes.length?inv.runes.map(x=>({precisao:'🎯 Precisão • centro ampliado',loki:'🃏 Loki • chance de pontuação dupla',thor:'⚡ Thor • combos mais valiosos',heimdall:'👁️ Heimdall • estabilidade da mira'}[x])).join('<br>'):'Nenhuma ainda. Abra baús para encontrar runas.')+'</div></div>';$('openChest').onclick=openChest;$('icePower').onclick=()=>usePower('gelo');$('firePower').onclick=()=>usePower('fogo')}
let oldMove=window.moveTarget||moveTarget;window.moveTarget=moveTarget=function(){if(activePower==='gelo'&&Date.now()<powerUntil){cancelAnimationFrame(motion);return}if(activePower&&Date.now()>=powerUntil)activePower=null;return oldMove()};
let oldScore=window.scoreShot||scoreShot;window.scoreShot=scoreShot=function(x,y){let pre=score,preC=centers;oldScore(x,y);let gained=score-pre;if(gained>0&&activePower==='fogo'&&Date.now()<powerUntil)score+=gained;if(gained>0&&inv.runes.includes('loki')&&Math.random()<.08)score+=gained;if(score>best){best=score;localStorage.setItem('viking-best',best)}if(typeof save==='function')save();if(typeof hud==='function')hud()};
let oldCenter=window.center||center;window.center=center=function(){let c=oldCenter();if(inv.runes.includes('precisao'))c.r*=1.08;return c};
let oldWind=window.wind||wind;window.wind=wind=function(){oldWind();if(inv.runes.includes('heimdall')){windX*=.88;windY*=.88}};
let oldReward=window.reward||reward;window.reward=reward=function(n){if(inv.runes.includes('thor')&&combo>=5)n=Math.ceil(n*1.25);return oldReward(n)};
let oldFinish=window.finish||finish;window.finish=finish=function(){if(!running)return oldFinish();let eligible=gameMode!=='training',before=career.games;oldFinish();updateDock();if(eligible){let chance=centers>=3?.8:.35;if(Math.random()<chance){inv.chests++;saveR();setTimeout(()=>{popup('🎁 BAÚ CONQUISTADO!<br>Abra em TESOUROS');render()},900)}}};
let oldStart=window.start||start;window.start=start=function(m='normal'){activePower=null;powerUntil=0;let r=oldStart(m);updateDock();return r};
ensureUI();let li=$('liveIce'),lf=$('liveFire');if(li)li.onclick=()=>usePower('gelo');if(lf)lf.onclick=()=>usePower('fogo');updateDock();})();