(()=>{const $=id=>document.getElementById(id);let peakLevel=1;
function stars(){let acc=shots?hits/shots:0,s=1;if(acc>=.65)s++;if(acc>=.8)s++;if(peakCombo>=8)s++;if(centers>=5||peakLevel>=30)s++;return Math.min(5,s)}
function history(){try{return JSON.parse(localStorage.getItem('viking-history')||'[]')}catch(e){return[]}}
function addHistory(){let h=history();h.unshift({at:Date.now(),mode:gameMode,score,hits,shots,acc:shots?Math.round(hits/shots*100):0,level:peakLevel,centers,combo:peakCombo,stars:stars()});localStorage.setItem('viking-history',JSON.stringify(h.slice(0,10)))}
function modeName(m){return({normal:'Normal',daily:'Diário',training:'Treino',survival:'Sobrevivência',bossrush:'Boss Rush'})[m]||m}
function enhanceProfile(){let p=$('profileContent');if(!p)return;let sb=+(localStorage.getItem('viking-survival-best')||0),bc=+(localStorage.getItem('viking-bossrush-count')||0),h=history();p.innerHTML+='<div class="rewardSummary"><div class="rewardTitle">⚔️ MODOS ESPECIAIS</div><div class="rewardGrid"><div class="rewardBox"><b>'+sb+'</b>Recorde Sobrevivência</div><div class="rewardBox"><b>'+bc+'</b>Boss Rush vencidos</div></div></div><div class="rewardSummary"><div class="rewardTitle">📜 ÚLTIMAS PARTIDAS</div><div class="rewardExplain">'+(h.length?h.map(x=>'⭐'.repeat(x.stars)+' <b>'+modeName(x.mode)+'</b> • '+x.score+' pts • '+x.acc+'% • Nv.'+x.level).join('<br>'):'Nenhuma partida registrada ainda.')+'</div></div>'}
let orp=window.renderProfile||renderProfile;window.renderProfile=renderProfile=function(){let r=orp();enhanceProfile();return r};
let ost=window.start||start;window.start=start=function(m='normal'){peakLevel=1;let r=ost(m);peakLevel=level;return r};
let os=window.scoreShot||scoreShot;window.scoreShot=scoreShot=function(x,y){let r=os(x,y);peakLevel=Math.max(peakLevel,level);return r};
let of=window.finish||finish;window.finish=finish=function(){if(!running)return of();peakLevel=Math.max(peakLevel,level);addHistory();let st=stars(),mode=gameMode,r=of();if(mode==='bossrush'&&localStorage.getItem('viking-bossrush-cleared')==='1'){let k='viking-bossrush-count',n=+(localStorage.getItem(k)||0)+1;localStorage.setItem(k,n);localStorage.removeItem('viking-bossrush-cleared')}setTimeout(()=>{let i=$('intro');if(i)i.innerHTML+='<div class="rewardSummary"><div class="rewardTitle">'+('⭐'.repeat(st))+'</div><div class="rewardExplain" style="text-align:center">Avaliação da partida • nível máximo '+peakLevel+'</div></div>';renderProfile()},850);return r};
})();