(()=>{const $=id=>document.getElementById(id);let peer=null,conn=null,role='',room='',opp={score:0,hits:0,shots:0,level:1,ready:false},sentEnd=false;
function code(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function loadPeer(cb){if(window.Peer)return cb();let s=document.createElement('script');s.src='https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js';s.onload=cb;s.onerror=()=>popup('❌ Falha ao carregar o multiplayer');document.head.appendChild(s)}
function status(t){let e=$('mpStatus');if(e)e.innerHTML=t}
function panel(){let home=$('home');if(!home||$('openMultiplayer'))return;let b=document.createElement('button');b.className='btn daily';b.id='openMultiplayer';b.textContent='🌐 DUELO ONLINE • 2 JOGADORES';let ref=$('openCompetition')||$('openProfile');ref?ref.after(b):home.appendChild(b);let p=document.createElement('div');p.className='panel';p.id='multiplayer';p.innerHTML='<h3>🌐 DUELO ONLINE</h3><div class="how"><b>DOIS CELULARES EM TEMPO REAL</b><br>Um jogador cria a sala e envia o código. O outro entra com o mesmo código. A partida começa quando os dois estiverem conectados.</div><div id="mpStatus" class="profileCard">Desconectado</div><button class="btn" id="mpCreate">CRIAR SALA</button><input id="mpCode" maxlength="6" placeholder="CÓDIGO DA SALA" style="width:100%;margin-top:8px;padding:13px;border-radius:12px;text-transform:uppercase;font-size:18px;text-align:center"><button class="btn sub" id="mpJoin">ENTRAR NA SALA</button><button class="btn" id="mpBack">VOLTAR</button>';home.parentElement.appendChild(p);b.onclick=()=>{home.style.display='none';document.querySelectorAll('.panel').forEach(x=>x.classList.remove('open'));p.classList.add('open')};$('mpBack').onclick=()=>{p.classList.remove('open');home.style.display='block'};$('mpCreate').onclick=create;$('mpJoin').onclick=join}
function bind(c){conn=c;c.on('open',()=>{status('🟢 Conectado • preparando duelo');send({t:'hello'});setTimeout(()=>{if(role==='host')send({t:'start',at:Date.now()+1200})},500)});c.on('data',data=>{if(!data||!data.t)return;if(data.t==='hello'){opp.ready=true;if(role==='host')setTimeout(()=>send({t:'start',at:Date.now()+1200}),300)}if(data.t==='start')begin(data.at);if(data.t==='state'){opp=data;renderLive()}if(data.t==='end'){opp={...opp,...data};result()}});c.on('close',()=>status('🔴 Adversário desconectou'));c.on('error',()=>status('❌ Erro de conexão'))}
function send(o){try{if(conn&&conn.open)conn.send(o)}catch(e){}}
function create(){loadPeer(()=>{room=code();role='host';status('⏳ Criando sala...');peer=new Peer('viking-'+room.toLowerCase());peer.on('open',()=>status('🏹 Sala <b>'+room+'</b><br>Envie este código ao outro jogador.'));peer.on('connection',c=>{if(conn&&conn.open){c.close();return}bind(c)});peer.on('error',e=>status('❌ '+(e.type==='unavailable-id'?'Código ocupado. Crie outra sala.':'Falha na conexão'))})}
function join(){let v=($('mpCode').value||'').trim().toUpperCase();if(v.length<4)return status('Digite o código da sala.');room=v;role='guest';loadPeer(()=>{status('⏳ Entrando em '+room+'...');peer=new Peer();peer.on('open',()=>bind(peer.connect('viking-'+room.toLowerCase(),{reliable:true})));peer.on('error',()=>status('❌ Não foi possível entrar na sala'))})}
function begin(at){let wait=Math.max(0,(+at||Date.now())-Date.now());status('⚔️ Duelo iniciando...');setTimeout(()=>{sentEnd=false;opp={score:0,hits:0,shots:0,level:1,ready:true};start('online');clearInterval(timer);time=60;hud();timer=setInterval(()=>{time--;hud();sync();if(time<=0)finish()},1000);$('msg').textContent='🌐 DUELO ONLINE'},wait)}
function sync(){send({t:'state',score,hits,shots,level,time});renderLive()}
function renderLive(){if(gameMode!=='online'||!running)return;let e=$('mpLive');if(!e){e=document.createElement('div');e.id='mpLive';e.style.cssText='position:absolute;z-index:29;top:78px;left:15%;right:15%;padding:6px;border-radius:12px;background:#07130de8;border:1px solid #ffe080;text-align:center;font:900 10px system-ui';game.appendChild(e)}e.style.display='block';e.textContent='🌐 VOCÊ '+score+' × '+(opp.score||0)+' ADVERSÁRIO'}
function result(){if(gameMode!=='online')return;let e=$('mpLive');if(e)e.style.display='none';let a=score,b=+(opp.score||0),r=a>b?'🏆 VOCÊ VENCEU!':a===b?'🤝 EMPATE!':'⚔️ ADVERSÁRIO VENCEU';setTimeout(()=>popup(r+'<br>'+a+' × '+b),650)}
let oh=window.hud||hud;window.hud=hud=function(){let r=oh();if(gameMode==='online')renderLive();return r};
let os=window.scoreShot||scoreShot;window.scoreShot=scoreShot=function(x,y){let r=os(x,y);if(gameMode==='online')sync();return r};
let of=window.finish||finish;window.finish=finish=function(){let online=gameMode==='online',final={t:'end',score,hits,shots,level};if(online&&!sentEnd){sentEnd=true;send(final)}let r=of();if(online)result();return r};
panel();})();