(()=>{const $=id=>document.getElementById(id);let lives=5,bossRushIndex=0,bossMode=false;
function ensureModes(){let home=$('home');if(!home||$('playSurvival'))return;let t=$('playTraining'),s=document.createElement('button');s.className='btn sub';s.id='playSurvival';s.textContent='❤️ SOBREVIVÊNCIA • 5 VIDAS';t.parentNode.insertBefore(s,t.nextSibling);let b=document.createElement('button');b.className='btn sub';b.id='playBossRush';b.textContent='👑 BOSS RUSH • 7 CHEFES';s.parentNode.insertBefore(b,s.nextSibling);s.onclick=()=>start('survival');b.onclick=()=>start('bossrush')}
function bossName(l){return({10:'BERSERKER',20:'FANTASMA',30:'LOKI',40:'JÖTUNN',50:'GUARDIÃO',60:'THOR',70:'ODIN'})[l]||'CHEFE'}
function bossBar(){let bar=$('bossBar');if(!bar){bar=document.createElement('div');bar.id='bossBar';bar.style.cssText='display:none;position:absolute;z-index:28;top:78px;left:12%;right:12%;background:#170b0be8;border:1px solid #e7bf62;border-radius:12px;padding:6px;text-align:center;font:900 10px system-ui;color:#ffe28a';game.appendChild(bar)}if(level%10===0&&running){let hp=Math.max(0,3-levelProgress);bar.style.display='block';bar.innerHTML='👑 '+bossName(level)+' • '+'❤️'.repeat(hp)+'🖤'.repeat(3-hp)}else bar.style.display='none'}
let oa=window.applyLevel||applyLevel;window.applyLevel=applyLevel=function(){let r=oa();bossBar();return r};
let oh=window.hud||hud;window.hud=hud=function(){let r=oh();bossBar();if(gameMode==='survival')$('time').textContent='❤️ '+lives;if(gameMode==='bossrush')$('time').textContent='👑 '+(bossRushIndex+1)+'/7';return r};
let ost=window.start||start;window.start=start=function(m='normal'){lives=5;bossRushIndex=0;bossMode=m==='bossrush';let r=ost(m);if(m==='survival'){clearInterval(timer);time=9999;hud();$('msg').textContent='❤️ SOBREVIVÊNCIA • 5 VIDAS'}if(m==='bossrush'){clearInterval(timer);time=9999;level=10;startLevel=10;levelProgress=0;applyLevel();place(1);hud();$('msg').textContent='👑 BOSS RUSH'}return r};
let os=window.scoreShot||scoreShot;window.scoreShot=scoreShot=function(x,y){let preHits=hits,preLevel=level;os(x,y);if(gameMode==='survival'&&hits===preHits){lives--;vibrate([80,50,80]);if(lives<=0){$('msg').textContent='💀 FIM DA SOBREVIVÊNCIA';setTimeout(()=>finish(),250)}else hud()}if(gameMode==='bossrush'&&preLevel%10===0&&level!==preLevel){bossRushIndex++;if(bossRushIndex>=7){coins+=50;earned+=50;stats.earned+=50;save();popup('🏆 ODIN DERROTADO • 🪙 +50');setTimeout(()=>finish(),600)}else{level=(bossRushIndex+1)*10;levelProgress=0;applyLevel();place(1);hud()}}bossBar()};
let of=window.finish||finish;window.finish=finish=function(){let mode=gameMode,lv=level,r=of();if(mode==='survival'){let best=+(localStorage.getItem('viking-survival-best')||0);if(lv>best)localStorage.setItem('viking-survival-best',lv)}if(mode==='bossrush'&&bossRushIndex>=7)localStorage.setItem('viking-bossrush-cleared','1');return r};
ensureModes();})();